### ISSUE TITLE
Display time remaining on ;work

### ISSUE THREAD

**Issue by GRektK** [cheesenibbles123/OliverbotPublic#3]
#### Solution:
When you do ;work, unless you live in CEST or know the conversion from CEST to your local time it can be annoying to figure out when you can work next. Personally I just guess until it lets me do it. I suggest you change the text from:

>You cannot work yet! You must wait until ddd HH:MM:SS CEST"

Where HH:MM:SS represents the time you are allowed to work in CEST to:

>You must wait **HH hr(s):MM min(s):SS sec(s)** to work again!

or something to that effect, where HH:MM:SS represents the _time remaining_ until you can work again. For added effect, you could also bold the time remaining although this is more of a nitpick. This would entirely remove the time conversion aspect making the system much more user friendly.

#### Alternatives:
In the past you have expressed interest in allowing users to set a timezone and then have it display in their timezone when they run the command. This would work, but the primary issue is that you would have to get every user's timezone or rely on them knowing that they can set it themselves which would be difficult and require some hands on management to get it started. Additionally, when someone else runs the command you would not be able to quickly identify when they can work again unless you recognize and can quickly convert their timezone. This is not nearly as important but it would cause more confusion.

#### Additional context:
Cum Fart archie bad? sometimes LOL plz fix ur assbot

**Comment by cheesenibbles123** [comment]
Added a time remaining section. I'll keep the original `You cannot work yet! You must wait until Tue 01 : 48 : 03 CEST` as this way I can keep the template and apply an offset when I get the timezones working, it's not so much an issue of the conversion itself being difficult, just need to actually setup the system to do it. The work card now has an extra section just below saying how much time is left in the HH : MM : SS format.

Before:
![image](https://user-images.githubusercontent.com/56054349/109493828-f800b600-7a84-11eb-9e3d-c2ca106f9bab.png)

After:
![image](https://user-images.githubusercontent.com/56054349/109493803-eb7c5d80-7a84-11eb-9827-2609df40f063.png)


Don't think I'll add **hr(s)** **min(s)** **sec(s)** just because it would make it harder to read / put in more clutter.

**Comment by cheesenibbles123** [comment]
System works and is now implemented fully.
